# Generated by Django 2.2.4 on 2021-01-23 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('school', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('mascot', models.CharField(max_length=50)),
                ('wins', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('game_number', models.AutoField(primary_key=True, serialize=False)),
                ('week_number', models.IntegerField(default=1)),
                ('home_team_score', models.IntegerField(default=0)),
                ('away_team_score', models.IntegerField(default=0)),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='away_team', to='Conference.Team')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='home_team', to='Conference.Team')),
                ('loser', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='loser', to='Conference.Team')),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='winner', to='Conference.Team')),
            ],
        ),
    ]
